ui5-community/wdi5

wdio-ui5-service/src/lib/WDI5.js, wdio-ui5-service/test/ui5.test.js
so far, focus() on a selected <control> worked
but delivered the wrong return value,
incorrectly reporting an error
=> feat: support $control.focus() properly

.github/workflows/wdi5-tests.js.yml, package.json, test/wdio-browser-withUI5tooling.conf.js, test/wdio-browser.conf.js, wdi5/README.md, wdi5/lib/BrowserUtils.js, wdi5/package.json, wdio-ui5-service/README.md, wdio-ui5-service/test/wdio-ui5-late.conf.js, wdio-ui5-service/test/wdio-ui5-literal.conf.js, wdio-ui5-service/test/wdio-ui5.conf.js, yarn.lock
when runnning against ui5 tooling,
calling $index html is necessary for starting the app;
as to where either ui5 tooling dir index middleware is used
or any other webserver that has dir index capability
-> don't explicitly call index.html and respect dir index
-> OR call $index file when set to sth other than "index.html"
=> fix: differentiate web server env

wdio-ui5-service/README.md, wdio-ui5-service/package.json
Hi, just tested the initial setup myself again and noticed that the `@wdio/sync` package is needed. Not sure if wdio provided it with earlier releases. 
But this should be at least mentioned some. Otherwise test execution wont start.
=> chore(wdio/sync): add dependency @wdio/sync

.github/workflows/wdi5-tests.js.yml, .github/workflows/wdio-ui5-service-tests.js.yml, .nvmrc, README.md, package.json, test/ui5-app/webapp/test/e2e/fluent-async-api.test.js, wdio-ui5-service/src/lib/wdioUi5-index.js, wdio-ui5-service/test/_selectorList.js, wdio-ui5-service/test/regex.test.js, wdio-ui5-service/test/screenshot.test.js, wdio-ui5-service/test/ui5-async.test.js, wdio-ui5-service/test/wdio-ui5-async.conf.js
this PR enables to `await` a method chain on a retrieved UI5 control:
```js
const title = await browser.asControl(listSelector).getItems(1).getTitle()
expect(title).toBe('Andrew Fuller')
```
this should not only reduce refactoring efforts on existing, `sync`-style notation tests, but also leads to more concise code.
without the fluent async api, the above example would have been:
```js
const list = await browser.asControl(listSelector)
const item = await list.getItems(1)
const title = await item.getTitle()
expect(title).toBe('Andrew Fuller')
```
additionally, tests in `wdio-ui5-service/test` got restructured so they can run in parallel, cutting down test-/ci-time.
=> feat: fluent async api

README.md
Heyo 👋
just looked a bit through the documentation and thought why not correct the typos I found.
I haven't found any PR template so I hope this will do (especially since it's just a simple typo PR ...)
You might want to have a look at the some links within the documentation e.g. "[See test/wdio-ui5.conf.js for a sample configuration file for browser-scope testing.](https://github.com/js-soft/wdi5/tree/main/wdio-ui5-service#:~:text=See%20test/wdio%2Dui5.conf.js%20for%20a%20sample%20configuration%20file%20for%20browser%2Dscope%20testing.)" which will redirect to a [404 ](https://github.com/js-soft/wdi5/blob/main/wdio-ui5-service/test/wdio-ui5.conf.js).  Maybe strictly point them towards the `main` branch or something? 
BR,
Marco
=> docs(readme): fixed up a few typos

examples/ui5-js-app/webapp/test/e2e/basic.test.js, examples/ui5-js-app/webapp/view/Main.view.xml, src/lib/wdi5-bridge.ts, src/lib/wdi5-control.ts
- change wdio selector from id to xpath
- basic check for selector structure
=> Enable special characters in UI5 control ids

client-side-js/injectTools.js, examples/ui5-js-app/jsconfig.json, src/lib/wdi5-bridge.ts
this PR provides a generic hook to insert browser-scope helper for wdi5.  
as a fist, compare versions from https://github.com/omichelsen/compare-versions#readme is used
=> chore: inject browser-scope helpers/tools

client-side-js/injectUI5.js, examples/ui5-js-app/package.json, examples/ui5-js-app/wdi5-multiversion.js, examples/ui5-js-app/wdio-webserver.conf.js, examples/ui5-js-app/webapp/test/e2e/generated-methods.test.js, examples/ui5-js-app/webapp/test/e2e/hash-nav.test.js, examples/ui5-js-app/webapp/test/e2e/interaction.test.js, examples/ui5-js-app/webapp/test/e2e/list-interaction.test.js, examples/ui5-js-app/webapp/test/e2e/locators-basic.test.js, examples/ui5-js-app/webapp/test/e2e/locators-regex.test.js, examples/ui5-js-app/webapp/test/e2e/pageObjects/Main.js, examples/ui5-js-app/webapp/test/e2e/pageObjects/Other.js, examples/ui5-js-app/webapp/test/e2e/press.test.js, examples/ui5-js-app/webapp/test/e2e/properties-matcher.test.js, package-lock.json, package.json, src/lib/wdi5-bridge.ts, src/types/browser-commands.ts
- wdi5 now determines the versions correctly and throws an wdi5 and wdio error if the ui5 version is below 1.60
- removed the `getUI5VersionAsFloat` function and it's usage, as it will not return the correct version in some cases.
- Instantiate the matchers correctly when the ui5 version is below 1.72
- added a dedicated properties-matcher script
- fixed some minor bugs in the multiversion script
Next step would be to integrate the multiversion script in the pipeline as well
=> Feat/164 introduce 1.60 as min UI5 Version

client-side-js/_navTo.js, client-side-js/injectUI5.js, client-side-js/interactWithControl.js
Remove unnecessary version checks (below version 1.60) and replace the `parseFloat` checks with `semver`
=> Fix: Version Checks

.gitignore, client-side-js/executeControlMethod.js, client-side-js/fireEvent.js, client-side-js/getControl.js, client-side-js/getSelectorForElement.js, client-side-js/injectUI5.js, client-side-js/interactWithControl.js
There is ~1.2sec delay on every sap.ui.test.waitForUI5() function call since the call adds unresolved promise into _promiseWaiter pipeline. This change skips extra Promise creation to speed up waitForUI5() function execution
https://github.com/js-soft/wdi5/issues/196
=> feat: using custom waitForUI5 with callbacks instead of Promises

docs/index.html
Your docs are under the path `/wdi5/`. 
Since the favicon was not explicitly specified in `index.html`, this path is not used.
Therefor a 404 error pops up.
Add explicit definition of the `favicon.ico` with wdi5 path to the index.html.
Works in my fork:
https://marianfoo.github.io/wdi5/#/
=> docs: fix favicon

.github/workflows/wdi5-tests.js.yml, examples/ui5-js-app/package.json, examples/ui5-js-app/scripts/getBrowsers.js, examples/ui5-js-app/wdio-docker-selenium.conf.js, examples/ui5-js-app/wdio-docker.conf.js, examples/ui5-js-app/wdio.base.conf.js, examples/ui5-ts-app/wdio-ui5.conf.ts, package.json
start test with eg.
```
npm run test:webserver -w examples/ui5-js-app -- --spec /basic.test.js --browsers firefox chrome
```
and/ or
```
npm run test:webserver -w examples/ui5-js-app -- --spec /basic.test.js --headless --debug
```
=> feat: change all ENV variables to arguments

client-side-js/executeControlMethod.js, client-side-js/injectUI5.js
- introduce collapseObject for flattening the inheritance Prototype
this avoids deletion of original object's properties,
causing unintended side effects
- rm unused window.wdi5...
- isCyclic
- removeCyclic
- should fix #275
=> fix: avoid referenced object manipulation (#275)

docs/installation.md
`sap.base` and `sap.ui.test` are no independent libraries. They are just namespaces which both are provided by the `sap.ui.core` library. Since this library is more or less mandatory for every UI5 Application we can remove this prerequisite completely.
Closes #300
=> fix: remove wrong library prerequisites from the docs

CHANGELOG.md
Since Version `0.9.1` the Headings for the Verions are `H3` instead of `H2` as previously.
Could not really tell what changed, maybe `standard-version`?
I´d like to parse changelog.md for changes and this would not work here.
I don't know if a manual change is appropriate here, but I'll just create the PR.
There is already an issue with changing the standard-version anyway #293
=> Adjust Markdown Headings for Versions in `CHANGELOG.md`

src/lib/wdi5-bridge.ts, src/lib/wdi5-control.ts
Improves the error messages when the control was not found and further actions are tried.
- The `press` and `getAggregation` throw now a readable error, when the control was not found. Also the actions don't wait for the wdio timeout anymore
- The determination, if it is a proxied (fluent async api) or real element, was removed from the `press` event and is now handled centrally in `getWebElement`
- If additional functions were executed via the fluent async api (that are not `press` or `enterText`) on a not found control there were cryptic errors for the user which are now more readable.
Closes #304
=> Improve error messages when control is not found

docs/usage.md, examples/ui5-js-app/webapp/test/e2e/error-logging.test.js, src/lib/wdi5-bridge.ts, src/lib/wdi5-control.ts, src/types/wdi5.types.ts
A new property `logging` (default: `true`) is added to the wdi5 selectors. When `logging` is set to `false` no logs will be written and shown in the terminal for this specific selector.
Closes #331
=> Selector specific logging

src/service.ts, src/types/wdi5.types.ts
As now all wdi5 specific properties are optional we can make the whole wdi5 config object optional as well. 
To not break existing code, we have to add the wdi5 object programmatically to allow for further checks on this wdi5 object
=> Make wdi5 config optional

src/lib/wdi5-bridge.ts, src/service.ts
In some cases the redirection and the loading of the ui5 application takes a little bit longer. Currently wdi5 does not wait for that after the authentication.
=> fix: wait for the injection of wdi5 till the redirection finished

docs/usage.md
This missing information has caused some headache for me, so I figured I add it to the docs to make life easier for others. @vobu has already confirmed this information is true here https://github.com/ui5-community/wdi5/issues/248#issuecomment-1122320737
=> Docs clarification for fluent async api

client-side-js/executeObjectMethod.js, client-side-js/getObject.js, examples/ui5-ts-app/src/controller/Main.controller.ts, examples/ui5-ts-app/test/e2e/Basic.test.ts
=> feat: allow for async client-side controller functions

client-side-js/injectUI5.js, examples/ui5-js-app/webapp/test/e2e/aggregation.test.js
A solution for #416 . Calculates the UUID using getRandomValues() until randomUUID() is only available in secure contexts (HTTPS and localhost).
=> Make saveObject() work in unsecure contexts

examples/ui5-ts-app/test/e2e/Basic.test.ts, examples/ui5-ts-app/test/e2e/Input.test.ts, examples/ui5-ts-app/test/e2e/MultiInput.test.ts, examples/ui5-ts-app/test/e2e/Navigation.test.ts, examples/ui5-ts-app/test/e2e/multiremote.test.ts, src/types/browser-commands.ts
this change provides a better DevX when `wdi5` is used w/ TS.
before: 
```ts 
const multiInput = (await browser.asControl(multiInputSelector)) as unknown as MultiInput
```
after: 
```ts
const multiInput = await browser.asControl<MultiInput>(multiInputSelector)
```
other samples "after":
```ts
const allButtons = await browser.allControls<Button>(allButtonsSelector)
const allButtonsOne = await browser.one.allControls<Button>(allButtonsSelector)
const navButton = await browser.asControl<Button>({
selector: {
id: "NavFwdButton",
viewName: "test.Sample.tsapp.view.Main"
}
})
await navButton.press()
```
_caveat_: this does not apply to the fluent async api!
(kudos to @jkoenig134 for the jumpstart!)
=> feat: enhanced types

.github/workflows/publish-btp.yml
both jobs run on the same time, but the job `publish-sample-ts-app-to-btp` depends on the build from job `build-sample-ts-app` That´s why deploy job failed because the artifact simply does not exist yet
https://github.com/ui5-community/wdi5/actions/runs/4261099722
closes #432
=> fix: publish btp workflow

client-side-js/testLibrary.js, src/lib/wdi5-fe.ts
- use correct given(arrangements), when(actions), then(assertions) assignement
- improve performance by reducing the amount of browser/node context switches. Should speed up the tests by about (~10%-20%)
- improve the error messages of the test library
Closes #448
=> fix: testLibrary improvements

docs/index.html, package.json
add feature to docs `copy to clipboard` from https://github.com/jperasmus/docsify-copy-code
also add `docsify-cli` to package.json so you can run the `startDoc` command and not need to install the cli yourself or globally
=> docs: add `copy to clipboard` to code snippets

src/types/wdi5.types.ts
Fixes https://github.com/ui5-community/wdi5/issues/544
This PR provides the types for WDI5Control to be used by people building typed matchers. It adheres to the naming-convention of being lowercase in the export. Additionally, we just export the type, as noone outside the framework should be able to instantiate a WDI5Control.
=> fix(types): expose types of WDI5Control via wdi5.types.ts

client-side-js/executeControlMethod.cjs, client-side-js/executeObjectMethod.cjs, client-side-js/getObject.cjs, client-side-js/injectUI5.cjs
After going deep down the rabbit hole, it turns out that the binding context object in already a small FE app is _humongously_ huge. Thus, when (in Node.js) a `getBindingContext()` is called on a located control for subsequent asserts on the binding object, the binding context object transferred between the browser- and the Node.js-scope is > 100 MB (!), causing serialisation operations fail.
This PR "cleans" the located controls internal object properties already in browser-scope by removing all private properities (starting with `_`) and `null` Array members.
The "cleaned" object is then only a fraction of its original size, (hopefully) making everyone more happy.
Closes #557
=> fix: remove empty array elements to reduce scope transfer size

package.json
The types are exported and should be able to be used by library consumers. However, when these consumers use recommended TypeScript `moduleResolution` setting "node16" (https://www.typescriptlang.org/tsconfig#moduleResolution), that will force the resolution to follow what is declared in the `exports` section of `package.json` -- where an explicit export of the types is currently missing.
Note that this is different from the `types` field at the top-level of `package.json`, which is a legacy mechanism for the old module resolution (this comment explains it pretty well for a different project, which dropped support for the legacy approach: https://github.com/typescript-eslint/typescript-eslint/pull/7186#issuecomment-1631373279).
As wdi5 is released with dual packaging (commonjs + esm), and …
=> fix: explicitly add types to exports

client-side-js/injectXHRPatch.cjs, docs/configuration.md, examples/ui5-js-app/e2e-test-config/wdio-ui5tooling.conf.js, examples/ui5-js-app/package.json, examples/ui5-js-app/scripts/delayedMockServer.js, examples/ui5-js-app/ui5.yaml, examples/ui5-js-app/webapp/Component.js, examples/ui5-js-app/webapp/localService/metadata.xml, examples/ui5-js-app/webapp/proxyrc.json, package-lock.json, src/lib/wdi5-bridge.ts, src/types/wdi5.types.ts
Add the option to skip the XHRWaiter an the fetchWaiter based on an regex in the wdi5 config.
=> feat: add option to ignore urls for auto waiting

examples/ui5-ts-app/package.json, package-lock.json
As browserstack suggests:
The @wdio/browserstack-service version you are using will result in inconsistent test results being reported to Test Observability and will impact all the metrics reported. Test Observability is an AI-driven test reporting, debugging & analytics solution.
We will soon be deprecating the usage of @wdio/browserstack-service versions lower than v7.34.0 (for users of WebdriverIO v7) or v8.24.6 (for WebdriverIO v8). Please upgrade at the earliest to continue utilising all the benefits of Test Observability.
=> update wdio broserstack service

src/lib/authentication/BasicAuthenticator.ts
This PR will fix #615 where the content of the .env file is simply put inside the URL. But instead it should be encoded before used in an URL.
=> fix: basic authentication (#615)

.github/workflows/wdi5-tests_auth.yml, docs/authentication.md, examples/ui5-ts-app/.gitignore, examples/ui5-ts-app/package.json, examples/ui5-ts-app/test/e2e/AuthenticationCert.test.ts, examples/ui5-ts-app/test/e2e/authentication/wdio-cert-authentication.conf.ts, examples/ui5-ts-app/wdio-ui5.conf.ts, package-lock.json, package.json, src/lib/authentication/CertAuthenticator.ts, src/lib/wdi5-bridge.ts, src/types/wdi5.types.ts
first PoC to authenticate with a SAP Passport Certificate to BTP using playwright and abstraction package [`playwright-client-certificate-login`](https://www.npmjs.com/package/playwright-client-certificate-login)
currently, to make this work, put pfx file to folder `ui5-ts-app` and rename it to sap.pfx and put your passphrase to in the [CertAuthenticator.ts](https://github.com/ui5-community/wdi5/blob/fd67a0b6e7db82738fa61560ecb155ae00619370/src/lib/authentication/CertAuthenticator.ts#L28) and run `npm run authentication:btp`.
This is just a PoC, needs better testing cases and proper config handling in the `CertAuthenticator.ts`.  
Still work to do but it works locally, should also work on pipelines
=> feat(auth): new auth with cert service

package-lock.json, package.json
This PR replaces the deprecated Fiori elements preview/mockserver with the well maintained [open source version](https://github.com/SAP/open-ux-odata/tree/main/packages/ui5-middleware-fe-mockserver) of it.
I am assuming it works as before because I executed the following commands in sequence without any problems
* `npm i`
* `npm run build`
* `npm test`
* `npm run test-h:js-app`
Note: I see log entries like the one below when running `test-h:js-app` but I cannot judge if this is an issue or not
```
[0-19] [wdi5] call of _getControl() failed because of: Error: No DOM element found using the control selector {"id":"__appointment0-container-Sample---Calendar--PC1-1-__row0-container-Sample---Calendar--PC1-1-5"}
[0-19] [wdi5] error retrieving control: …
```
=> fix(deps): switch to oss mockserver
