ui5-community/wdi5

docs/advanced.md, lib/WDI5.js, package.json
for method chaining
- fireEvent
- toogle
- check
- uncheck
- press
- enterText
- setProperty
=> feat(methodchaining): wdi5 change return types

README.md
- check
- uncheck
- toggle
change return types for all events
=> docs(readme): add WDI5 function description

test/ui5-app/webapp/test/e2e/pageObjects/Main.js, test/ui5-app/webapp/test/e2e/pageObjects/Other.js, test/ui5-app/webapp/test/e2e/pageObjects/Page.js, test/ui5-app/webapp/test/e2e/test-aggregation.js, test/ui5-app/webapp/test/e2e/test-ui5-cb.js
- page obejcts example for easier reuse -> can be extended
=> feat(pageobjects): create main and other

.gitignore, package.json, wdio-ui5-service/README.md, wdio-ui5-service/src/lib/wdioUi5-index.js, wdio-ui5-service/src/service.js, wdio-ui5-service/test/ui5-late.test.js, wdio-ui5-service/test/wdio-ui5-late.conf.js, wdio-ui5-service/test/wdio-ui5.conf.js
thanks to @mikezaschka for the feature request
=> feature: add option to skip UI5 initialization on startup

.prettierrc, .vscode/settings.json, wdi5/index.js, wdio-ui5-service/src/lib/WDI5.js, wdio-ui5-service/src/lib/wdioUi5-index.js, wdio-ui5-service/test/ui5-late.test.js, wdio-ui5-service/test/ui5.test.js, wdio-ui5-service/test/wdio-ui5-literal.conf.js, wdio-ui5-service/test/wdio-ui5.conf.js
this PR adds the possibility to locate controls via a regular expression in the "id" selector
minor:
- test restructurings
- kick in prettier on save
=> feat: locate ui5 controls via id regex

wdio-ui5-service/src/lib/wdioUi5-index.js
- wrapper to the getAggregation result control into an array
=> fix(aggregation): when getAggregation returns only one control

wdio-ui5-service/src/lib/WDI5.js
issue occured by creating control ids
=> :bug: fixed issue retrieving only on element by getAggregation 

wdio-ui5-service/src/lib/WDI5.js
fixes stale elements in getAggregation
=> added this._forceSelect to asControl-calls in WDI5.js

README.md, wdio-ui5-service/README.md, wdio-ui5-service/src/lib/WDI5.js, wdio-ui5-service/src/lib/wdioUi5-index.js
I need guidance on how to document & test
=> Enables the override of the WaitForUI5 timeout

wdi5/package.json, wdio-ui5-service/src/lib/WDI5.js, wdio-ui5-service/src/lib/wdioUi5-index.js, wdio-ui5-service/test/regex.test.js, wdio-ui5-service/test/ui5-async.test.js
=> fix: make partial property text regex work

package.json, test/ui5-app/webapp/test/e2e/aggregation.test.js, test/ui5-app/webapp/view/Other.view.xml, wdio-ui5-service/src/lib/WDI5.js, yarn.lock
fixing unintended side effects of get$Shorthand(0) -
get$Shorthand(1..n) worked fine!
closes #124
=> fix(aggregation): shorthand access for index 0

docs/_sidebar.md, docs/locators.md, docs/usage.md, examples/ui5-js-app/wdio-webserver.conf.js, examples/ui5-js-app/webapp/test/e2e/bindingpath-matcher.test.js, examples/ui5-js-app/webapp/test/e2e/i18n-matcher.test.js, examples/ui5-js-app/webapp/test/e2e/matcher.test.js, examples/ui5-js-app/webapp/test/e2e/properties-matcher.test.js, examples/ui5-js-app/webapp/view/Main.view.xml
- docs for bespoken
- prep "todo"-style tests of locator-/matcher-combinations yet untested
=> docs: locators aka matchers

docs/contributing.md, docs/installation.md, docs/running.md
add section "reinitialize setup"
=> docs: update installation.md

client-side-js/injectUI5.js
might be helpful eg. if you would like to check in the test which kind of control was retrieved.
=> feat(controlMethods): rm getMetadata from filtered methods

examples/ui5-js-app/wdio-ui5-late.conf.js, examples/ui5-js-app/wdio-ui5tooling.conf.js, examples/ui5-js-app/wdio-webserver.conf.js, examples/ui5-js-app/wdio.base.conf.js, package.json
- make it more easy to see the key differences between configs.
- easier to maintain
- already a preparation for two additional configs coming in with the docker PR
=> refactor: add wdio.base.conf to point out key differences

package.json
This reverts commit b17685c68c3f51ca1bf8b013b49eac90de1f9c73.
Sorry, we will now store the metadata in the [source.json](https://github.com/ui5-community/ui5-community.github.io/blob/main/packages/crawler/sources.json).
I have already extended your [PR](https://github.com/ui5-community/ui5-community.github.io/pull/83/commits/6a9688fb828129dd244285b188d5b61d92f8cf59).
=> Revert "feat: add to "best of UI5" (#231)"

client-side-js/executeControlMethod.js, client-side-js/getControl.js, client-side-js/injectUI5.js, examples/ui5-js-app/webapp/test/e2e/basic.test.js, src/lib/wdi5-control.ts
- still basic implementation
- to discuss: best way of remove circular
- todo: add tests to prove
for #224
=>  return value of method call can be object

docs/_sidebar.md, docs/fe-testlib.md
documentation how to integrate the Fiori Elements OData v4 test library in wdi5
=> docs: :memo: fiori elements odata v4 test library integration

client-side-js/injectUI5.js
fix typo in the errorHandling
Closes #296
=> fix: remove typo from error handling

src/types/wdi5.types.ts
Add missing optional property "searchOpenDialogs" to selector type
=> feat: add searchOpenDialogs to wdi5ControlSelector type

docs/recipes.md
wrong code
Just rename varibale
Regarding this comment here
`const fileName = "wdi5-logo.png" // relative to wdio.conf.(j|t)s`
I tried this, but for me it was relative to where i executed the command, not where wdio.conf was.
=> fix(docs): fix js code uploadFile

docs/installation.md
adds information to installation.md in regards to #408
=> change installation.md

docs/authentication.md, src/lib/authentication/BTPAuthenticator.ts
code and documentation for issue: BTP supporting multiple identity providers #510
=> feat: supporting multiple identity providers (#510)
